### PR TITLE
HB 

### PR DESCRIPTION
**Pull request by hobertbush**
Hey @BrandonFinch  and @ialodah,

I have so really cool code to add to the main after your review...

Updated readme and added preprocessing file.

### CODE REVIEW

**Comment by BrandonFinch** [comment]
Hey Team,

I am reviewing the code now!

**Comment by ialodah** [comment]
I approve :)

**Comment by hobertbush** [comment]
Thank you both!

**Review by BrandonFinch — APPROVED** [review]
Everything looks good!

**Review by ialodah — APPROVED** [review]

**Pull request merged**
